# Generated by Django 4.1.5 on 2023-02-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('foto1', models.ImageField(null=True, upload_to='noticias/media')),
                ('foto2', models.ImageField(null=True, upload_to='noticias/media')),
                ('foto3', models.ImageField(null=True, upload_to='noticias/media')),
                ('foto4', models.ImageField(null=True, upload_to='noticias/media')),
                ('foto5', models.ImageField(null=True, upload_to='noticias/media')),
            ],
        ),
    ]
